network: ""
ethClient: ""
beaconClient: ""
mysqlDsn: ""
logLevel: ""
slackUrl: ""
checkVerifyWithdrawCredential:
  enable: false
  intervalBlock: 0
  firstRun: 0
  batchSize: 0
checkStartCheckPoint:
  enable: false
  intervalBlock: 0
  firstRun: 0
  batchSize: 0
checkQueueWithdraw:
  enable: false
  intervalBlock: 0
  firstRun: 0
  batchSize: 0
checkVerifyCheckPoint:
  enable: false
  intervalBlock: 0
  firstRun: 0
  batchSize: 0
keyAgent:
  keyAgentRpc: ""
  service: 0
  index: 0
  address: ""
  signPri: ""
  keyAgentSignPub: ""
  keyAgentEncryptPub: ""