name: Go Test CI

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Install Unzip
      run: sudo apt-get install unzip
    - name: Unzip the File 1
      run: unzip data/deneb_goerli_slot_7413760.json.zip -d ./data
    - name: Unzip the File 2
      run: unzip data/goerli_slot_6397952.json.zip -d ./data
    - name: Unzip the File 3
      run: unzip data/deneb_goerli_slot_7431952.json.zip -d ./data
    - name: Unzip the File 3
      run: unzip data/deneb_goerli_slot_7421952.json.zip -d ./data
    - name: Unzip the File 4
      run: unzip data/goerli_slot_6409723.json.zip -d ./data

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Run tests
      run: go test -v ./...